/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SucessoRouteImport } from './routes/sucesso'
import { Route as PremiumRouteImport } from './routes/premium'
import { Route as EstimativaRouteImport } from './routes/estimativa'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AtendimentoRouteImport } from './routes/atendimento'
import { Route as AjudaRouteImport } from './routes/ajuda'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FluxoDevolutivaRouteImport } from './routes/fluxo.devolutiva'
import { Route as FluxoComprarVenderRouteImport } from './routes/fluxo.comprar-vender'
import { Route as FluxoCertidaoRouteImport } from './routes/fluxo.certidao'

const SucessoRoute = SucessoRouteImport.update({
  id: '/sucesso',
  path: '/sucesso',
  getParentRoute: () => rootRouteImport,
} as any)
const PremiumRoute = PremiumRouteImport.update({
  id: '/premium',
  path: '/premium',
  getParentRoute: () => rootRouteImport,
} as any)
const EstimativaRoute = EstimativaRouteImport.update({
  id: '/estimativa',
  path: '/estimativa',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AtendimentoRoute = AtendimentoRouteImport.update({
  id: '/atendimento',
  path: '/atendimento',
  getParentRoute: () => rootRouteImport,
} as any)
const AjudaRoute = AjudaRouteImport.update({
  id: '/ajuda',
  path: '/ajuda',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FluxoDevolutivaRoute = FluxoDevolutivaRouteImport.update({
  id: '/fluxo/devolutiva',
  path: '/fluxo/devolutiva',
  getParentRoute: () => rootRouteImport,
} as any)
const FluxoComprarVenderRoute = FluxoComprarVenderRouteImport.update({
  id: '/fluxo/comprar-vender',
  path: '/fluxo/comprar-vender',
  getParentRoute: () => rootRouteImport,
} as any)
const FluxoCertidaoRoute = FluxoCertidaoRouteImport.update({
  id: '/fluxo/certidao',
  path: '/fluxo/certidao',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ajuda': typeof AjudaRoute
  '/atendimento': typeof AtendimentoRoute
  '/dashboard': typeof DashboardRoute
  '/estimativa': typeof EstimativaRoute
  '/premium': typeof PremiumRoute
  '/sucesso': typeof SucessoRoute
  '/fluxo/certidao': typeof FluxoCertidaoRoute
  '/fluxo/comprar-vender': typeof FluxoComprarVenderRoute
  '/fluxo/devolutiva': typeof FluxoDevolutivaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ajuda': typeof AjudaRoute
  '/atendimento': typeof AtendimentoRoute
  '/dashboard': typeof DashboardRoute
  '/estimativa': typeof EstimativaRoute
  '/premium': typeof PremiumRoute
  '/sucesso': typeof SucessoRoute
  '/fluxo/certidao': typeof FluxoCertidaoRoute
  '/fluxo/comprar-vender': typeof FluxoComprarVenderRoute
  '/fluxo/devolutiva': typeof FluxoDevolutivaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ajuda': typeof AjudaRoute
  '/atendimento': typeof AtendimentoRoute
  '/dashboard': typeof DashboardRoute
  '/estimativa': typeof EstimativaRoute
  '/premium': typeof PremiumRoute
  '/sucesso': typeof SucessoRoute
  '/fluxo/certidao': typeof FluxoCertidaoRoute
  '/fluxo/comprar-vender': typeof FluxoComprarVenderRoute
  '/fluxo/devolutiva': typeof FluxoDevolutivaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ajuda'
    | '/atendimento'
    | '/dashboard'
    | '/estimativa'
    | '/premium'
    | '/sucesso'
    | '/fluxo/certidao'
    | '/fluxo/comprar-vender'
    | '/fluxo/devolutiva'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ajuda'
    | '/atendimento'
    | '/dashboard'
    | '/estimativa'
    | '/premium'
    | '/sucesso'
    | '/fluxo/certidao'
    | '/fluxo/comprar-vender'
    | '/fluxo/devolutiva'
  id:
    | '__root__'
    | '/'
    | '/ajuda'
    | '/atendimento'
    | '/dashboard'
    | '/estimativa'
    | '/premium'
    | '/sucesso'
    | '/fluxo/certidao'
    | '/fluxo/comprar-vender'
    | '/fluxo/devolutiva'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AjudaRoute: typeof AjudaRoute
  AtendimentoRoute: typeof AtendimentoRoute
  DashboardRoute: typeof DashboardRoute
  EstimativaRoute: typeof EstimativaRoute
  PremiumRoute: typeof PremiumRoute
  SucessoRoute: typeof SucessoRoute
  FluxoCertidaoRoute: typeof FluxoCertidaoRoute
  FluxoComprarVenderRoute: typeof FluxoComprarVenderRoute
  FluxoDevolutivaRoute: typeof FluxoDevolutivaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sucesso': {
      id: '/sucesso'
      path: '/sucesso'
      fullPath: '/sucesso'
      preLoaderRoute: typeof SucessoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/premium': {
      id: '/premium'
      path: '/premium'
      fullPath: '/premium'
      preLoaderRoute: typeof PremiumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estimativa': {
      id: '/estimativa'
      path: '/estimativa'
      fullPath: '/estimativa'
      preLoaderRoute: typeof EstimativaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atendimento': {
      id: '/atendimento'
      path: '/atendimento'
      fullPath: '/atendimento'
      preLoaderRoute: typeof AtendimentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ajuda': {
      id: '/ajuda'
      path: '/ajuda'
      fullPath: '/ajuda'
      preLoaderRoute: typeof AjudaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fluxo/devolutiva': {
      id: '/fluxo/devolutiva'
      path: '/fluxo/devolutiva'
      fullPath: '/fluxo/devolutiva'
      preLoaderRoute: typeof FluxoDevolutivaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fluxo/comprar-vender': {
      id: '/fluxo/comprar-vender'
      path: '/fluxo/comprar-vender'
      fullPath: '/fluxo/comprar-vender'
      preLoaderRoute: typeof FluxoComprarVenderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fluxo/certidao': {
      id: '/fluxo/certidao'
      path: '/fluxo/certidao'
      fullPath: '/fluxo/certidao'
      preLoaderRoute: typeof FluxoCertidaoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AjudaRoute: AjudaRoute,
  AtendimentoRoute: AtendimentoRoute,
  DashboardRoute: DashboardRoute,
  EstimativaRoute: EstimativaRoute,
  PremiumRoute: PremiumRoute,
  SucessoRoute: SucessoRoute,
  FluxoCertidaoRoute: FluxoCertidaoRoute,
  FluxoComprarVenderRoute: FluxoComprarVenderRoute,
  FluxoDevolutivaRoute: FluxoDevolutivaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
